server:
  port: 8000


spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/mrc0700
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true